= MCP Server Examples

Built Using Native https://github.com/modelcontextprotocol/java-sdk[MCP Java SDK] – No Spring Framework Required.

== Requirements
- Java 17 or later (Restricted by MCP Java SDK)

== What is MCP?

The https://modelcontextprotocol.io[Model Context Protocol (MCP)] lets you build servers that expose data and functionality to LLM applications in a secure, standardized way. Think of it like a web API, but specifically designed for LLM interactions. MCP servers can:

- Expose data through **Resources** (think of these sort of like GET endpoints; they are used to load information into the LLM's context)
- Provide functionality through **Tools** (sort of like POST endpoints; they are used to execute code or otherwise produce a side effect)
- Define interaction patterns through **Prompts** (reusable templates for LLM interactions)
- And more!

You can start exploring everything about *MCP* from https://modelcontextprotocol.io[here].

== Examples

These servers aim to demonstrate MCP features and the MCP Java SDK.

- https://github.com/codeboyzhou/mcp-java-sdk-examples/blob/main/mcp-server-filesystem/README.adoc[Filesystem] - Secure file operations with configurable access controls
