spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        enabled: true
        stdio: true
        name: mcp-stdio-server
        version: 1.0.0
        instructions: This is a mcp stdio server example.
        type: SYNC
