= Filesystem MCP Server

Java server implementing Model Context Protocol (MCP) for filesystem operations.

== Features

- Read/write files from the local filesystem.

*Note*: The server will only allow operations within directories specified via `env`.

== API

=== Resources

- `file://system`: File system operations interface

=== Tools

- *read_file*
  * Read complete contents of a file
  * Input: `path` (string)
  * Reads complete file contents with UTF-8 encoding

== Usage with MCP Client

You can use any MCP client such as Cursor (IDE) or Cline (VS Code plugin) to interact with MCP server.

=== Build

[source,bash]
----
mvn clean package
----

=== Configuration

*Note*: The `env` configuration is optional for access control.

`readable`: Read access control with regular expressions, format example: `["^/var/log/(app|sys)\.log$"]`.
`writable`: Write access control with regular expressions, format example: `["^/var/log/(app|sys)\.log$"]`.

[source,json]
----
{
  "mcpServers": {
    "mcp-server-filesystem": {
      "command": "java",
      "args": [
        "-jar",
        "${your_jar_path}/mcp-server-filesystem.jar"
      ],
      "env": {
        "permission": {
          "readable": [],
          "writable": []
        }
      }
    }
  }
}
----
