= Filesystem MCP Server

Java server implementing Model Context Protocol (MCP) for filesystem operations.

== Features

- Read file from the local filesystem.
- List files of a directory from the local filesystem.

*Note*: The server will only allow operations within directories specified via `env`.

== API

=== Resources

- `file://system`: File system operations interface.

=== Tools

- *read_file*
  * Read complete file contents with UTF-8 encoding.
  * Input:
    ** `path` (string): The path to the file to read.
  * Output: Complete file contents with UTF-8 encoding.

- *list_files*
  * List files of a directory with name-based filtering and recursion option.
  * Input:
    ** `directoryPath` (string): The path to the directory to read.
    ** `fileNamePattern` (string): Regular expression to filter files, if it's empty, all files will be listed. Default is empty.
    ** `recursive` (boolean): Whether to list files recursively. Default is `false`.
  * Output: A list of file names (paths if 'recursive' is `true`), or empty string if no files are found.

=== Prompt

- *read_file*
  * For `read_file` tool
  * Input: `filepath` (string)
  * Output: What is the content of this file: `<filepath>`

- *list_files*
  * For `list_files` tool
  * Input: `directoryPath` (string), `fileNamePattern` (string), `recursive` (boolean)
  * Output:
    ** Please list files in this directory: `<directoryPath>`
    ** Please list files in this directory: `<directoryPath>`, with file name pattern: `<fileNamePattern>`
    ** Please list files in this directory: `<directoryPath>`, with file name pattern: `<fileNamePattern>`, recursively

== Usage with MCP Client

You can use any MCP client such as Cursor (IDE) or Cline (VS Code plugin) to interact with MCP server.

=== Build

[source,bash]
----
mvn clean package
----

=== Configuration

*Note*: The `env` configuration is optional for access control.

`readable`: Read access control with regular expressions, format example: `["^/var/log/(app|sys)\.log$"]`.

`writable`: Write access control with regular expressions, format example: `["^/var/log/(app|sys)\.log$"]`.

[source,json]
----
{
  "mcpServers": {
    "mcp-server-filesystem": {
      "command": "java",
      "args": [
        "-jar",
        "${your_jar_path}/mcp-server-filesystem.jar"
      ],
      "env": {
        "permission": {
          "readable": [],
          "writable": []
        }
      }
    }
  }
}
----
